#ifndef TRACK_PARAMS_H
#define TRACK_PARAMS_H

const float PIXELS_SECOND_THRESH = 10.;
const float PIXELS_SECOND_GROUP_THRESH = 30.;
const float FRAMES_SECOND=15.;
const float GROUP_THRESH = PIXELS_SECOND_GROUP_THRESH / FRAMES_SECOND;
const unsigned int NUM_VELOC_FRAMES = 15;
const float MVTHRESH = PIXELS_SECOND_THRESH / FRAMES_SECOND;

#endif
